#!/usr/bin/env bash
# This script displays the content of current directory with only the part after the first dash
for file in ./*; do
    filename=$(basename "$file")
    echo "${filename#*-}"
done
