#!/bin/bash
python3 -c "import os;w='water';s='stir.';b='bestchol';W=os.environ['WATER'];S=os.environ['STIR'];n=sum(w.index(c)*len(w)**i for i,c in enumerate(reversed(W)))+sum(s.index(c)*len(s)**i for i,c in enumerate(reversed(S)));r='';exec("while n:\\n r=b[n%len(b)]+r\\n n//=len(b)");print(r)"
